FROM ubuntu:bionic

ARG REPO=golanggrpc
ARG CONTAINER_NAME="${REPO}-base"

ENV GO_VERSION=1.12.9
ENV GOLINTER_VERSION=1.17.1
ENV PROTOC_VERSION=3.8.0

ENV REPO=${REPO}
ENV CONTAINER_NAME=${CONTAINER_NAME}
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH /usr/local/go/bin:${PATH}

RUN apt-get update \
  && apt-get install -y \
       build-essential \
       ca-certificates \
       curl \
       gettext-base \
       git \
       jq \
       libssl-dev \
       make \
       python3 \
       python3-pip \
       unzip \
       vim \
       wget \
       yamllint \
       zip \
  && apt-get clean

# some utilities
RUN curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip \
  && unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local bin/protoc \
  && unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local include/* \
  && rm -rf protoc-${PROTOC_VERSION}-linux-x86_64.zip \
  && curl -O https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz \
  && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz \
  && rm -rf go${GO_VERSION}.linux-amd64.tar.gz

# Install golinter into /usr/local/bin and keep GOPATH clean
WORKDIR /usr/local
RUN curl -O https://install.goreleaser.com/github.com/golangci/golangci-lint.sh \
  && sh ./golangci-lint.sh v${GOLINTER_VERSION} \
  && rm -rf golangci-lint.sh
