version: '3.3'
services:
  alpinebase:
    build:
      context: .
      dockerfile: Dockerfile-alpinebase
  alpinebuild:
    build:
      context: .
      dockerfile: Dockerfile-alpinebuild
      args:
        - USER_ID
        - GROUP_ID
    command: tail -f /dev/null
    user: ${USERID}
    environment:
      - EC_GOLANGGRPC_DEBUG=true
    tty: true
    stdin_open: true
    volumes:
      - .:/home/builder/src
  alpineapi:
    build:
      context: .
      dockerfile: Dockerfile-alpineapi
    environment:
      - EC_GOLANGGRPC_DEBUG=true
      - EC_GOLANGGRPC_PORT=8080
    ports:
      - "8080:8080"
