version: '3.3'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile-base
  build:
    build:
      context: .
      dockerfile: Dockerfile-build
      args:
        - USER_ID
        - GROUP_ID
    command: tail -f /dev/null
    user: ${USERID}
    environment:
      - GOLANGGRPC_LOGLEVEL=DEBUG
    tty: true
    stdin_open: true
    volumes:
      - .:/home/builder/src
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    environment:
      - GOLANGGRPC_LOGLEVEL=DEBUG
      - GOLANGGRPC_PORT=8080
    ports:
      - "8080:8080"
