---
version: '3.3'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile-base
      args:
        - REPO
  builder:
    depends_on:
      - base
    build:
      context: .
      dockerfile: Dockerfile-builder
      args:
        - GUID
        - REPO
        - USER
        - UUID
        - GODIR
    tty: true
    stdin_open: true
    volumes:
      - .:/home/builder/src
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    environment:
      - GOLANGGRPC_LOGLEVEL=DEBUG
      - GOLANGGRPC_PORT=8080
    ports:
      - "8080:8080"
