---
version: '3.3'
services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile-base
      args:
        - REPO_NAME
  builder:
    depends_on:
      - base
    build:
      context: .
      dockerfile: docker/Dockerfile-builder
      args:
        - GODIR
        - GUID
        - REPO_NAME
        - USER
        - UUID
    tty: true
    stdin_open: true
    volumes:
      - .:/home/${USER}/${REPO_NAME}
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile-api
    environment:
      - GOLANGGRPC_LOGLEVEL=DEBUG
      - GOLANGGRPC_PORT=8080
    ports:
      - "8080:8080"
