version: '3.3'
services:
  alpinebase:
    build:
      context: .
      dockerfile: Dockerfile-alpinebase
  alpine:
    build:
      context: .
      dockerfile: Dockerfile-alpine
    command: tail -f /dev/null
    environment:
      - EC_GOLANGGRPC_DEBUG=true
    tty: true
    stdin_open: true
    volumes:
      - .:/src
  alpineapi:
    build:
      context: .
      dockerfile: Dockerfile-alpineapi
    environment:
      - EC_GOLANGGRPC_DEBUG=true
      - EC_GOLANGGRPC_PORT=8080
    ports:
      - "8080:8080"
