FROM ubuntu:focal

ARG REPO_NAME=golanggrpc
ARG CONTAINER_NAME="${REPO_NAME}-base"

ENV GO_VERSION=1.14.2
ENV GOLINTER_VERSION=1.24.0
ENV PROTOC_VERSION=3.11.4
ENV PROTOBUF_VERSION=1.3.3

ENV REPO_NAME=${REPO_NAME}
ENV CONTAINER_NAME=${CONTAINER_NAME}
ENV PATH=/usr/local/go/bin:${PATH}

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
  && apt-get upgrade -y --no-install-recommends \
  && apt-get install -y \
       build-essential \
       ca-certificates \
       curl \
       gettext-base \
       git \
       jq \
       libssl-dev \
       make \
       python3 \
       python3-pip \
       unzip \
       vim \
       wget \
       yamllint \
       zip \
  && apt-get autoremove \
  && apt-get autoclean \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# protoc
RUN curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip \
  && unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local bin/protoc \
  && chmod +x /usr/local/bin/protoc \
  && unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local include/* \
  && rm -rf protoc-${PROTOC_VERSION}-linux-x86_64.zip

# go
RUN curl -O https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz \
  && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz \
  && rm -rf go${GO_VERSION}.linux-amd64.tar.gz

WORKDIR /usr/local
# Install golinter into /usr/local/bin
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v${GOLINTER_VERSION}
